/**
 * 
 */
package com.bas.KU.services;

import java.util.Map;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;

/**
 * @author San
 *
 */
public class ThirdPartyServiceImpl implements ThirdPartyService {

	@Override
	public void sendMail() {
		final String user = "sanoop.pits@yahoo.com";
		final String password = "minisivan";
		final String host = "smtp.mail.yahoo.com";
		final String portNo = "465";
		Properties props = new Properties();
		props.put("mail.smtp.host", host);
		props.put("mail.smtp.socketFacry.port", portNo);
		props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.port", portNo);
		Session session = Session.getInstance(props, new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(user, password);
			}
		});
		sendMail(session, user);
		// sendAutogeneratedMail(user, name, email, session);

	}

	@Override
	public void sendSMS() {

		String sResult = null;
		try {
			// Construct data
			String phonenumbers = "9995176461";
			String data = "user=" + URLEncoder.encode("sanoop56", "UTF-8");
			data += "&password=" + URLEncoder.encode("9995176461", "UTF-8");
			data += "&message=" + URLEncoder.encode("hi hello", "UTF-8");
			data += "&sender=" + URLEncoder.encode("INVITE", "UTF-8");
			data += "&mobile=" + URLEncoder.encode(phonenumbers, "UTF-8");
			data += "&type=" + URLEncoder.encode("3", "UTF-8");
			// Send data
			URL url = new URL("http://login.bulksmsgateway.in/sendmessage.php?" + data);
			URLConnection conn = url.openConnection();
			conn.setDoOutput(true);
			OutputStreamWriter wr = new OutputStreamWriter(conn.getOutputStream());
			wr.write(data);
			wr.flush();
			// Get the response
			BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			String line;
			String sResult1 = "";
			while ((line = rd.readLine()) != null) {
				// Process line...
				sResult1 = sResult1 + line + " ";
			}
			wr.close();
			rd.close();

		} catch (Exception e) {
			System.out.println("Error SMS " + e);

		}
	}
	// TODO Auto-generated method stub

	public void sendMail(Session session, String user) {

		String to = "sanoopsivan.s.m@gmail.com";// change accordingly

		// Get the session object

		// Compose the message
		try {

			String subject = "sample";
			String messageBody = "sample body";
			MimeMessage message = new MimeMessage(session);
			MimeBodyPart messageBodyPart = new MimeBodyPart();
			messageBodyPart.setContent(messageBody, "text/html" + ";charset=utf-8");
			Multipart multipart = new MimeMultipart();
			multipart.addBodyPart(messageBodyPart);
			message.setContent(multipart);
			message.setSubject(subject);
			message.setFrom(new InternetAddress(user));
			message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

			// send the message
			Transport.send(message);

		} catch (MessagingException e) {
			e.printStackTrace();
		}
	}

}
